### ISSUE TITLE
你好；能问下 你的文章都是写在这里面的吗？

### ISSUE THREAD

**Issue by 931743010** [zchen9/zchen9.github.io#6]
为什么 我下载整个项目 下来 都看不见  你的文章内的内容呢？  一个也没看见；其实我是想找下 你文章里面 如何插入音乐的。       为啥文章 不在呢 不是 都在 _posts下面的吗？

**Comment by zchen9** [comment]
这个repo只是放了主页😂 
有音乐的文章都在fragment那个repo里面 直接用网易云音乐的分享插件就好

**Comment by 931743010** [comment]
- - 好吧 这样分离好高级      两边 我怎么都没看出来  是在一起了
