### ISSUE TITLE
多个滚动条的问题0.0

### ISSUE THREAD

**Issue by XFeiF** [zchen9/zchen9.github.io#8]
http://www.chen9.info/code/Whats-this   右侧会出现三个滚动条，在上一层/code/右侧会出现两个滚动条0.0，应该不是故意留下的吧

**Comment by XFeiF** [comment]
可能是由于嵌套的关系吧，Hexo和Ghost应该差不多都是有一套结构。

**Comment by zchen9** [comment]
你在什么浏览器上看到的这个问题？ 我没找到。。。

**Comment by XFeiF** [comment]
不好意思，要开学了，别的事有点多，才看到邮件。
额，chrome浏览器,试了一下Edge，好像也是这样。

2016-08-27 16:33 GMT+08:00 照澄 <notifications@github.com>:

**Comment by AeroYoung** [comment]
服务器停了？看不到了呢。
